// src/templates/monorepo/apps/client/src/App.tsx
import { useState } from 'react';
import { API_VERSION } from '@${projectName}/shared';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="min-h-screen bg-gray-100">
      <header className="bg-white shadow">
        <div className="max-w-7xl mx-auto py-6 px-4">
          <h1 className="text-3xl font-bold text-gray-900">
            ${projectName} (API v{API_VERSION})
          </h1>
        </div>
      </header>
      <main className="max-w-7xl mx-auto py-6 px-4">
        <div className="bg-white shadow rounded-lg p-6">
          <button
            onClick={() => setCount(count + 1)}
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
          >
            Count is {count}
          </button>
        </div>
      </main>
    </div>
  );
}

export default App;

// src/templates/webapp-solid/src/App.tsx
import type { Component } from 'solid-js';
import { Routes, Route } from '@solidjs/router';
import { Home } from './pages/Home';
import { About } from './pages/About';

export const App: Component = () => {
  return (
    <div class="min-h-screen bg-gray-100">
      <nav class="bg-white shadow">
        <div class="max-w-7xl mx-auto px-4">
          <div class="flex justify-between h-16">
            <a href="/" class="flex items-center">
              <span class="text-xl font-bold">My App</span>
            </a>
            <div class="flex items-center space-x-4">
              <a href="/" class="text-gray-700 hover:text-gray-900">Home</a>
              <a href="/about" class="text-gray-700 hover:text-gray-900">About</a>
            </div>
          </div>
        </div>
      </nav>
      <main class="max-w-7xl mx-auto py-6 px-4">
        <Routes>
          <Route path="/" component={Home} />
          <Route path="/about" component={About} />
        </Routes>
      </main>
    </div>
  );
};
